M48
; DRILL file {KiCad (7.0.0)} date Fri Mar  3 13:32:33 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-03-03T13:32:33+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0433
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X4.3421Y-3.1232
X4.3421Y-3.2232
T2
X5.6791Y-3.0421
X5.6791Y-3.802
X7.8689Y-3.0421
X7.8689Y-3.802
T0
M30
